### PR TITLE
Bugfix owncloud success text

### PR DESCRIPTION
**Pull request by linucksrox**
This resolves issue #581

### CODE REVIEW

**Comment by linucksrox** [comment]
Can someone please help me understand why this failed? Literally all I did was add color to some text, which seems completely unrelated to this build error.

**Comment by rivaldi8** [comment]
I'm not sure why it has failed, however, it would be good if you get rid of commit d7d15fc. There should be only your commit. It looks like you branched from master and sent the pull request against develop.

You can fix it by rebasing your branch into develop and push it again with `--force`.

**Comment by linucksrox** [comment]
I'm not understanding this. You're right that I branched from master, then sent the pull request against develop. Should I have branched from develop instead of master? Thanks for working with me, this is my first real pull request.

**Comment by rivaldi8** [comment]
Yes, you should usually branch from the branch where you'll send the pull request. If you branch from another one by mistake or if you change your mind later, you can fix it like this:
```
git checkout bugfix-owncloudSuccessText
git rebase develop
git push --force
```
This will take all the changes you made in your branch and reapply them on top of develop. The `--force` will tell git to overwrite whatever changes you pushed before.

Let me know if you need more help.

**Comment by linucksrox** [comment]
I realize now that I should have branched from hotfix/patches, it looks like commit dae1caf fixes the issue I'm having here. I'm closing this pull request to open a new one. Thanks for the help!

**Comment by linucksrox** [comment]
Thanks again. I did try rebasing and force pushing that branch, but still ran into the failing test again. I see that your most recent pull request was against hotfix/patches which also contains a fix for the build error. I know the contribution guide says to send the PR to develop, but would it be better for me to send the PR to hotfix/patches since that branch seems to be the only one that is passing tests right now? Or do I need to wait?

**Comment by rivaldi8** [comment]
It should be ok to send PR with small fixes to hotfix/patches.

**Comment by linucksrox** [comment]
Ok, thanks for letting me know.

**Pull request closed without merging**
