### PR TITLE
Small ScheduledActionTest refactor

### PR DESCRIPTION
**Pull request by rivaldi8**
Depends on #530

### CODE REVIEW

**Comment by codinguser** [comment]
What happened here? :)

**Comment by rivaldi8** [comment]
I selected the wrong base branch :) Maybe you could set the default branch to `develop` or `hotfix/patches` (see [Setting the default branch](https://help.github.com/articles/setting-the-default-branch/)). What do you think?

**Comment by codinguser** [comment]
I'll think about it. 
I considered it before, but thought it might cause people who just checkout to build the app for themselves to build a develop build. And those can be in a not so stable state.

**Comment by rivaldi8** [comment]
Yes, you are right. There should be a separate option for pull requests.

**Pull request closed without merging**
