### PR TITLE
Added ability to load GNUCash v. 3.0 xml

### PR DESCRIPTION
**Pull request by xzfantom**
#777 Now it's possible to load xml from desktop version 3.0

### CODE REVIEW

**Comment by codinguser** [comment]
Thanks @xzfantom

**Comment by businessBoris** [comment]
Oh man! I've just loaded gnucash (Linux desktop and mobile) again to try after many years hiatus.
This is a present from the gods.
Thank you very very much.

UPDATE: I was so excited that I was minded to reset SyncThing for the new setup now! Forgot about a little thing like the actual release of this update to 'production'! Doh!

**Comment by codinguser** [comment]
@businessBoris you could join the beta program if you would like to get your hands on it fast. It will hit there first

**Comment by codinguser** [comment]
Alright, no worries then. It'll come when it's fully baked.

**Comment by businessBoris** [comment]
Where do I find the find the actual xml on Android? I think it's hidden from me on Android 7.0
Happy to post to the wiki if that's a thing you want to do.

**Comment by xzfantom** [comment]
Gnucash Android don't use xml to store data, it uses internal SQLite database. Xml is used for import only.

**Comment by businessBoris** [comment]
Thank you.

**Pull request merged**
