### PR TITLE
Bugfix 604: Scheduled exports aren't executed if they're checked before the next run

### LINKED ISSUE #604: Scheduled exports aren't executed if they're checked before the next run
Scheduled exports won't be executed if the scheduled action service runs before the next run. The reason is that [ScheduledActionService.executeScheduledEvent](https://github.com/codinguser/gnucash-android/blob/d1c31033366ae7044e4b115b9ac021060660ef18/app/src/main/java/org/gnucash/android/service/ScheduledActionService.java#L145) sets the scheduled action's last run even if it hasn't actually been run. As the service runs twice a day, the period will never pass.
#### Software specifications
- GnuCash Android version: 2.1.3
- System Android version: 5.0
- Device type: bq Aquaris E4

### PR DESCRIPTION
**Pull request by rivaldi8**
I hope this time it's fixed for real. Please, check nothing else has slipped through.

Fixes #604

### CODE REVIEW

**Comment by rivaldi8** [comment]
Wait! don't merge it yet. I've just noticed that the transactions exported after the fix include the period since the scheduled export creation date instead of since the last export date. Not sure if it's something that should be fixed here, but I'd like to investigate first. I think there's an UserVoice ticket reporting a similar issue.

**Comment by rivaldi8** [comment]
It's ok to merge this pull request. I'll verify the other problem with some testing and I'll open another bug report for it.

**Comment by codinguser** [comment]
I'm planning to remove scheduled exports/backups to their own table and have their own service in v2.2.0 anyway. So I would advise to invest time only for critical stuff which affects users. 
Separating the scheduled backups and transactions will mean we have to redo most of this logic anyway, hopefully then in a more stable way.

**Comment by codinguser** [comment]
@rivaldi8 I got some reports of all transactions always being exported. That is one thing we should definitely fix ASAP since it affects user workflow. Please let me know if you find a cure :)

**Comment by rivaldi8** [comment]
Ok, I was working on these export-related bugs because I was affected by them :) I've also seen the one about all transactions being exported. I was about to work on it after fixing #609, which I thought it was related although I'm no longer sure.

**Pull request merged**
