### PR TITLE
Bugfix 641: Weekday is ignored in scheduled exports

### PR DESCRIPTION
**Pull request by rivaldi8**
Am I late for 2.2?

Please, check I haven't missed any corner case :)

### CODE REVIEW

**Comment by codinguser** [comment]
No, it's not late. I just wanted to get a first beta out as soon as
possible so we can get actual user feedback.

I'll check it when I get back to my desk. Thanks!

**Comment by rivaldi8** [comment]
Sorry, I forgot to switch back to the full unit test suite before sending the pull request. It seems the tests have to be updated to set `byDays` for weekly actions.

Today I have a busy day. I'll fix it tomorrow.

**Comment by rivaldi8** [comment]
It should be fixed now.

**Comment by codinguser** [comment]
Cool, thanks. So `byday` is always set by the recurrence dialog, right?

**Comment by rivaldi8** [comment]
Yes, the dialog forces you to set at least on weekday. However, after a more thorough inspection, I've found `GncXmlHandler` never sets the recurrence's `byDays`. It doesn't parse the weekdays.

Until we don't implement the parsing for imported weekly transaction, I'd add at least one weekday to `byDays`. We could just use the weekday of the start date. That way it would be executed at least once per week. In fact I'd say that's how it worked until now.

Also, although with a warning, GnuCash desktop allows you to define a weekly transaction without setting any weekday. In that case, it's never executed. So, I'll have to add a check for empty `byDays` too.

**Comment by codinguser** [comment]
@rivaldi8 sounds like a plan 👍

**Pull request merged**
