### PR TITLE
fix qif export to SDCard

### PR DESCRIPTION
**Pull request by fefe982**

### CODE REVIEW

**Comment by codinguser** [comment]
:+1: thanks :)

**Comment by rivaldi8** [comment]
@fefe982, beware this PR reverts the changes that fixed #357. Also, it's not considered good practice to have a method do more than what it's expected from its name (this confused me a lot while reading the code to fix the bug).

I think we should be careful with SD card operations. It seems there's some inconsistency in how different devices handle it's access. That may be the cause of the export issues.

**Comment by codinguser** [comment]
@rivaldi8 so does it mean that sharing multiple files (split into QIF) is what causes the sharing file to fail.
Also, we rely on the Android getExternalStorageDirectory API. The assumption is that this will return us a location where can safely store the files. 

In the future I'm thinking of changing that to use the cache for the temporary internal export before we move the file to the location desired by the user.

**Comment by codinguser** [comment]
@rivaldi8 I've already merged this request. 
I was just thinking, since you identified the cause of the problem with file sharing to 3rd party services, maybe we can fix it without breaking QIF exports. Any ideas?

**Comment by rivaldi8** [comment]
@codinguser The problem with file sharing is that `copyFile()` doesn't copy the file `src` to `dst`, if `src` is a Qif. Instead, it calls `splitQif()`, which splits `src` into multiple files with `dst` as file name suffix.

The general problem, I think, is that `splitQif()` should be only called once as part of the process of exporting to QIF. Then, all export options should deal with multiple files per export.

@fefe982 Could you describe the issue you are fixing with this PR so I can try to reproduce it?

**Comment by codinguser** [comment]
This issue being fixed is that QIF file was not  being split into the
different currencies.  Or at least, if it was, then only the original
unsplit version was given to the user as the result of the export.

@rivaldi8 Does this mean that the problem of not being able to export is
again present on your device after this patch?

If so then maybe we can do it as you suggest and  treat all exports as a
list of files. Which would be 1 for XML and multiple for OFX.
I'll look into it.

**Comment by rivaldi8** [comment]
Yes, it's failing again.

**Comment by rivaldi8** [comment]
@codinguser, are you working on this? If not, I can look into fixing it.

**Comment by codinguser** [comment]
@rivaldi8 please go ahead and look into it.
Won't have time the next few days
Thanks

**Comment by codinguser** [comment]
@rivaldi8 have you been able to look into it yet?

**Comment by rivaldi8** [comment]
Yes, I'm working on it.

**Comment by rivaldi8** [comment]
@codinguser It have taken more time than I thought but I've finally finished with the fix. I just need some more time to review the changes, do some further clean up, and testing. I'll send a pull request tomorrow.

**Comment by codinguser** [comment]
@rivaldi8 great! looking forward to it...

**Pull request merged**
