### PR TITLE
Bugfix 446: Edit button overlapped in transaction view

### PR DESCRIPTION
**Pull request by weslly99**
Fixes [446](https://github.com/codinguser/gnucash-android/issues/446)

### CODE REVIEW

**Comment by rivaldi8** [comment]
I wasn't affected by the bug, so I can't say whether the pull request fixes it or not. However, I can confirm it doesn't seem to introduce any problem in my device (bq Aquaris E4 - Android 5.0).

**Comment by weslly99** [comment]
This bug affect earlier version to lollipop. Do you can test in a device Android kitkat or Jellybean?
I tested in devices on Android  JellyBean and Kitcat and the result is described in issue #446 
The Shadow It still the same. It is due to reduction in size.
Device Moto Razr D3, Android Kitkat:
Before:
screenshot_2016-07-14-07-53-20

After
screenshot_2016-07-14-07-47-08

**Comment by rivaldi8** [comment]
I don't have any other device, however, I could finally test it from an emulator with KitKat (I was having problems in my computer). So I can now confirm it fixes the issue.

By the way, as we are preparing for the next release, would you mind rebasing the pull request onto the develop branch?

**Comment by weslly99** [comment]
Ok @rivaldi8, I'll close this pull request and open a new in develop branch

**Pull request closed without merging**
